### ISSUE TITLE
When doctrine:generate:entities - Error on TablePrefixSubscriber.php : getClassAnnotations() must be an instance of ReflectionClass 

### ISSUE THREAD

**Issue by hisem** [kayue/KayueWordpressBundle#35]
When I run the doctrine:generate:entities command on my projet, I get this error:

```
PHP Catchable fatal error:  Argument 1 passed to Doctrine\Common\Annotations\AnnotationReader::getClassAnnotations() must be an instance of ReflectionClass, null given, called in .../vendor/kayue/kayue-wordpress-bundle/Kayue/WordpressBundle/Subscriber/TablePrefixSubscriber.php on line 31 and defined in .../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php on line 153
```

I found a way to get around it here:
https://github.com/orocrm/platform/issues/5

by adding this to Subscriber\TablePrefixSubscriber.php:

```
use Doctrine\Common\Persistence\Mapping\RuntimeReflectionService;
public function loadClassMetadata(LoadClassMetadataEventArgs $args)
    {
        $classMetadata = $args->getClassMetadata();
        $rrs = new RuntimeReflectionService();
        $classMetadata->wakeupReflection($rrs);
[...]
```

though I honestly do not understand what's going on...

Does anyone else get this issue? Is it project-related? Can this work-around be used in any case and thus be added to this bundle?

Thanks.

**Comment by wujku** [comment]
I switch to last commit 451b5a19fdcadce6747125fe11a4c308a14cb528 and have that same issue when I run doctrine:generate:form. I use other connection for bundle.
